services:
  app:
    build: .
    container_name: fieldfinder_be
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - redis-master
#      - redis-sentinel-1
#      - redis-sentinel-2
#      - redis-sentinel-3
      - rabbitmq
      - mongo
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
    environment:
      # Chạy Redis Sentinel
#      - SPRING_DATA_REDIS_SENTINEL_MASTER=mymaster
#      - SPRING_DATA_REDIS_SENTINEL_NODES=redis-sentinel-1:26379,redis-sentinel-2:26379,redis-sentinel-3:26379
      - spring.data.redis.host=127.0.0.1
      - spring.data.redis.port=6379
      - spring.data.redis.connect-timeout=3000
      - spring.data.redis.timeout=3000
      - SPRING_DATA_REDIS_CONNECT_TIMEOUT=3000
      - SPRING_DATA_REDIS_TIMEOUT=3000
      # Chạy Redis Sentinel
#      - SPRING_REDIS_REDISSON_FILE=classpath:redisson-docker.yml
      - SPRING_REDIS_REDISSON_FILE=classpath:redisson-local.yml
      - SPRING_RABBITMQ_HOST=rabbitmq

  redis-master:
    image: redis:7-alpine
    container_name: redis-master
    ports:
      - "6379:6379"
    # Thêm bind và tắt protected-mode
    command: redis-server --bind 0.0.0.0 --protected-mode no --appendonly yes
    restart: always

#  redis-replica:
#    image: redis:7-alpine
#    container_name: redis-replica
#    ports:
#      - "6380:6380"
#    # Thêm bind và tắt protected-mode
#    command: redis-server --port 6380 --bind 0.0.0.0 --protected-mode no --replicaof redis-master 6379
#    depends_on:
#      - redis-master
#    restart: always
#
#  redis-sentinel-1:
#    image: redis:7-alpine
#    container_name: redis-sentinel-1
#    ports:
#      - "26379:26379"
#    # LƯU Ý: Dùng dấu gạch dọc | ở đây thay vì dấu >
#    command: |
#      sh -c "cat <<EOF > /tmp/sentinel.conf
#      port 26379
#      bind 0.0.0.0
#      sentinel resolve-hostnames yes
#      sentinel announce-hostnames yes
#      sentinel monitor mymaster redis-master 6379 2
#      sentinel down-after-milliseconds mymaster 30000
#      sentinel failover-timeout mymaster 60000
#      sentinel parallel-syncs mymaster 1
#      EOF
#      redis-sentinel /tmp/sentinel.conf --protected-mode no"
#    depends_on:
#      - redis-master
#      - redis-replica
#    restart: always
#
#  redis-sentinel-2:
#    image: redis:7-alpine
#    container_name: redis-sentinel-2
#    ports:
#      - "26380:26379"
#    command: |
#      sh -c "cat <<EOF > /tmp/sentinel.conf
#      port 26379
#      bind 0.0.0.0
#      sentinel resolve-hostnames yes
#      sentinel announce-hostnames yes
#      sentinel monitor mymaster redis-master 6379 2
#      sentinel down-after-milliseconds mymaster 30000
#      sentinel failover-timeout mymaster 60000
#      sentinel parallel-syncs mymaster 1
#      EOF
#      redis-sentinel /tmp/sentinel.conf --protected-mode no"
#    depends_on:
#      - redis-master
#      - redis-replica
#    restart: always
#
#  redis-sentinel-3:
#    image: redis:7-alpine
#    container_name: redis-sentinel-3
#    ports:
#      - "26381:26379"
#    command: |
#      sh -c "cat <<EOF > /tmp/sentinel.conf
#      port 26379
#      bind 0.0.0.0
#      sentinel resolve-hostnames yes
#      sentinel announce-hostnames yes
#      sentinel monitor mymaster redis-master 6379 2
#      sentinel down-after-milliseconds mymaster 30000
#      sentinel failover-timeout mymaster 60000
#      sentinel parallel-syncs mymaster 1
#      EOF
#      redis-sentinel /tmp/sentinel.conf --protected-mode no"
#    depends_on:
#      - redis-master
#      - redis-replica
#    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: fieldfinder_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    command: /bin/sh -c "rabbitmq-plugins enable --offline rabbitmq_stomp && rabbitmq-server"
    restart: always

  mongo:
    image: mongo:latest
    container_name: fieldfinder_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data: