spring.application.name=FieldFinder
server.error.include-message=always
server.forward-headers-strategy=framework

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

spring.data.mongodb.uri=mongodb+srv://triet172004_db_user:${MONGO_DB_PASSWORD}@fieldfinder.jgtptcb.mongodb.net/FieldFinder?retryWrites=true&w=majority
spring.data.mongodb.database=FieldFinder

payos.endpoint=https://api-merchant.payos.vn
payos.clientId=${YOUR_CLIENT_ID}
payos.apiKey=${YOUR_API_KEY}
payos.cancelUrl=http://localhost:3000/payment-cancel
payos.returnUrl=http://localhost:3000/payment-success
payos.checksumKey=${YOUR_CHECKSUM_KEY}
front_end_url=http://localhost:3000

weather_api_key=${WEATHER_API_KEY}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=triet172004@gmail.com
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-swallow-size=100MB

spring.cache.type=redis
spring.cache.redis.time-to-live=600000

#Redis Sentinel
#spring.data.redis.sentinel.master=mymaster
#spring.data.redis.sentinel.nodes=127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381
#spring.data.redis.connect-timeout=3000
#spring.data.redis.timeout=3000
#spring.redis.redisson.file=classpath:redisson.yml

spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.redis.redisson.file=classpath:redisson-local.yml

spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=2000ms
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.multiplier=2

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

jwt.secret=${JWT_SECRET}
jwt.access-token-ttl-seconds=1800
jwt.refresh-token-ttl-seconds=2592000

google.client-id=${GOOGLE_CLIENT_ID}

facebook.app-id=${FACEBOOK_APP_ID}
facebook.app-secret=${FACEBOOK_APP_SECRET}

passkey.rp-id=localhost
passkey.rp-name=FieldFinder
passkey.rp-origin=http://localhost:8080